apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-application
  namespace: my-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blue-app
  template:
    metadata:
      labels:
        app: blue-app
    spec:
      containers:
      - name: blue-app-container
        image: my-blue-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          value: jdbc:postgresql://db-service:/mydatabase

