
############## Config Map ################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-config-map
data:
  # property-like keys; each key maps to a simple value
  APP_COLOR: darkblue
  APP_OTHER: disregard


##Update the Pod spec to use the configMap as below:
##Inject with pod


---
apiVersion: v1
kind: Pod
metadata:
  labels:
    name: webapp-color
  name: webapp-color
  namespace: default
spec:
  containers:
  - env:
    - name: APP_COLOR
      valueFrom:
       configMapKeyRef:
         name: webapp-config-map
         key: APP_COLOR
    image: kodekloud/webapp-color
    name: webapp-color