##### Secret #######################
apiVersion: v1
kind: Secret
metadata:
  name: secret-sa-sample
data:
   DB_Host: YmFyCg==
   DB_User: hhdggd=
   DB_Pssword: shsggdjdnd=
##Add the secret in the pod spec as below
apiVersion: v1 
kind: Pod 
metadata:
  labels:
    name: webapp-pod
  name: webapp-pod
  namespace: default 
spec:
  containers:
  - image: kodekloud/simple-webapp-mysql
    imagePullPolicy: Always
    name: webapp
    envFrom:
    - secretRef:
        name: db-secret